services:
  pdf_analyser:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HF_TOKEN=${HF_TOKEN:-}
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - model_cache:/root/.cache
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - HF_TOKEN=${HF_TOKEN}

volumes:
  model_cache: